### ISSUE TITLE
Implement RFC0052: Graceful Stack Upgrades

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/go#651]
[RFC](https://github.com/paketo-buildpacks/rfcs/blob/main/text/0052-graceful-stack-upgrades.md)

## Summary

All Paketo Buildpacks should support graceful stack upgrades between the current Bionic and Jammy stacks. For most buildpacks, this should not require any changes, but for some buildpacks, layers created in previous builds that would normally be reused should be recreated if the stack ID changes.

## Action Item
Consider what types of buildpacks would be impacted by a stack upgrade and make any relevant changes that would help to mitigate issues caused by that upgrade. If there is no work to be done, please comment on this issue explaining the context that helped to arrive at that conclusion.

**Comment by sophiewigmore** [comment]
Hi @paketo-buildpacks/go-maintainers, I looked into this a bit today and so far I haven't seen any failures when upgrading stacks. I was focused on the Go Mod Vendor buildpack and the Go Build buildpack in testing.

For each of the following, I built the app with a bionic stack, then with a jammy stack and saw successful builds
- Built each app in https://github.com/paketo-buildpacks/go/tree/main/integration/testdata

- Added a modified version of the basic `go_mod` app, which imported `github.com/mattn/go-sqlite3`. This modification was meant to show an example of a module using CGO, which we have seen cause issues on Jammy Jellyfish in our automation. However, its presence caused no issues when upgrading to the Jammy stack.

- Built `jam` with the Go buildpack. I tried this because (1) we have seen issues with CGO-related dynamic linking when building binaries on one stack, and then using the binary on another OS, and (2) the `jam` library has more Go Modules and complicated code than other samples, which made it a good candidate to try out.

- I also tested the same scenarios by modifying the Go Dist buildpack to work on the `*` stack, using `index.docker.io/jericop/amazonlinux-builder:base` as the builder I switched to. I saw no failures this way either

**Comment by sophiewigmore** [comment]
I plan on digging in a bit deeper tomorrow on the Go Mod/Go Build buildpacks,  but as of now, I don't believe we need to add any cache invalidation additions to the buildpacks because I haven't yet encountered a scenario where this is an issue

**Comment by ryanmoran** [comment]
This outcome is kind of what I expected. It makes sense that the Go toolchain "does the right thing" in this case. I imagine that it is pulling down new code or rebuilding packages that have CGO bindings when the stack changes. I think the only concern we might have left to explore is whether the cache is getting bloated with extra built modules/packages that it no longer needs. My understanding is that the Go cache doesn't do any pruning, so this isn't a concern we should do anything about since we aren't currently pruning the cache for any other reasons.

Thanks @sophiewigmore for doing the exploration to confirm the behavior works as expected. Should we still include some tests?

**Comment by sophiewigmore** [comment]
@ryanmoran alright, looking at the build cache, it does seem like the modules are either cleaned up or had no change at all, but the cache from Go build gets slightly bloated. Here's the size differences when I built and then upgraded that [go mod app with CGO](https://github.com/paketo-buildpacks/go/tree/graceful-stack-upgrades/integration/testdata/cgo_app):

  | First Build (bionic) | Second Build (jammy) | Clean build (jammy)
-- | -- | -- | --
Go Mod Vendor layer | 13 M | 13 M | 13 M
Go Build layer | 73M | 85 M | 71 M

When performing the same experiment on building `jam`, I saw similar results. I'm not sure I'm worried enough about this to want to clear the go cache

**Comment by ryanmoran** [comment]
Great work, @sophiewigmore!
